import React from 'react'
import img from '../../images-videos/barber-conocenos.jpg'
import styles from './Conocernos.module.css'

export default function Conocernos() {
  return (
    <div className = {styles.contenedorConocernos}>
      <img src={img} alt="conocenos"  />
      <div className = {styles.contenedorTexto}>

        <h2>EZEQUIEL RESIPA - BARBERO PROFESIONAL</h2>

       <hr />


       <p>SOY <b>EZEQUIEL</b>, FUNDADOR DE ER BARBER, PELUQUERO PROFESIONAL Y BARBER ARTIST.</p>

       <p>MI PASIÓN POR LOS DETALLES Y LA BÚSQUEDA DE NUEVAS TENDENCIAS DE BELLEZA ME LLEVÓ POR UN CAMINO DE CONSTANTE APRENDIZAJE. ¿AUTODIDACTA? SI, POR SUPUESTO. PERO TAMBIÉN ME RELACIONÉ Y COMPARTÍ CONOCIMIENTOS CON LOS MEJORES ARTISTAS INTERNACIONALES.</p>

       <p>DESDE 2017 LIDERO MI BOUTIQUE ESPECIALIZADA EN PELUQUERIA SEMI PROFESIONAL (COLOR & CORTE FULL BARBER).</p>

       <p>¡LA BARBERIA ES MÁS DE LO QUE IMAGINAMOS! LO USAMOS PARA VERNOS Y SENTIRNOS MEJOR, IMPACTANDO POSITIVAMENTE EN NUESTRA AUTOESTIMA. INFLUYE TAMBIÉN EN LO QUE TRANSMITIMOS A LOS DEMÁS Y AUMENTA NUESTRA CONFIANZA PARA LOGRAR LO QUE NOS PROPONGAMOS. ES FASCINANTE NO? A VECES IMPLEMENTARLO A NUESTRA RUTINA DIARIA NO RESULTA FÁCIL. IMAGÍNATE LEVANTARTE TODOS LOS DÍAS Y ESTAR CON TU MEJOR CORTE! BUENO, ¡DE ESO NOS OCUPAMOS NOSOTROS!</p>

       <p>NUESTRO EQUIPO SE CONFORMA POR PROFESIONALES ALTAMENTE CAPACITADOS Y DEBIDAMENTE CERTIFICADOS CON EXPERIENCIA COMPROBADA. CADA UNO DE LOS INTEGRANTES FUE SELECCIONADO POR SU CAPACIDAD Y POR SU CALIDEZ HUMANA QUE SE VE PLASMADA EN EL TRATO Y LA ATENCIÓN QUE RECIBE NUESTRO PÚBLICO. EN OG NO SOLO BRINDAMOS UN SERVICIO DE CALIDAD, SINO UNA EXPERIENCIA.</p>

       <p>TAMBIÉN DISEÑAMOS CURSOS DE CAPACITACIÓN CON TÉCNICAS INNOVADORAS PARA SEGUIR FORMANDO CADA VEZ MÁS ARTISTAS. DESDE 2019 DICTAMOS NUESTROS CURSOS EN MIAMI USA, DEMOSTRANDO QUE NUESTRA FORMA DE TRABAJO Y LA CALIDAD DE LOS RESULTADOS QUE LOGRAMOS NO TIENE FRONTERAS.</p>

       <p>TENEMOS COMO OBJETIVO POTENCIAR LA BELLEZA NATURAL DE NUESTROS CLIENTES Y CONFIAMOS EN QUE MENOS ES MAS. POR ESO, CUIDAMOS LOS DETALLES, EVITANDO EXCESOS, Y APOSTANDO SIEMPRE A UN RESULTADO ARMÓNICO Y NATURAL.</p>

       <p>TE INVITO A QUE LOGREMOS JUNTOS TU MEJOR VERSIÓN.</p>

 

       <p><b>SE VOS MISMO.</b></p>

       <p><b>SIEMPRE.</b></p>

       <p><b>ER BARBER.</b></p>








      </div>
    </div>
  )
}
